[package]
name = "wiggly_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
# ttf-parser = "0.20.0"
owned_ttf_parser = { version = "0.20.0", default-features = false }
wasm-bindgen = "0.2.92"
